### ISSUE TITLE
Actualización para vagrant 1.7.2

### ISSUE THREAD

**Issue by josedom24** [iesgn/openstack-debian-ansible#16]
A partir de la versión 1.7.2 de vagrant se crea una clave privada para cada máquina. Por lo tanto no se puede acceder a las máquinas con la clave insegura vagrant_private_key.

Para saber donde está guardada la clave privada de cada máquina, hay que ejecutar la instrucción:
<pre>
$ vagrant ssh-config
Host controller
  HostName 127.0.0.1
  User vagrant
  Port 2222
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile /home/jose/github/openstack-debian-ansible/.vagrant/machines/controller/virtualbox/private_key
  IdentitiesOnly yes
  LogLevel FATAL

</pre>
Por lo tanto, hay que modificar el fichero ansible.cfg de la siguiente forma:
<pre>
...
private_key_file = .vagrant/machines/controller/virtualbox/private_key
...
</pre>

**Comment by albertomolina** [comment]
Pero, ¿es necesario utilizar una versión de vagrant <= 1.7.2?

Todo está hecho utilizando paquetes de Debian jessie (vagrant, virtualbox, ansible, etc.). Se podría actualizar el README poniendo una nota a usuarios con otra versión de vagrant, ¿no?

**Comment by josedom24** [comment]
No es necesario.
Simplemente, cuando la receta este terminada se puede actualizar el README y el fichero ansible.cfg para versiones más actuales de vagrant.

**Comment by albertomolina** [comment]
Listo en las últimas versiones
