### ISSUE TITLE
Problems loading horizon css

### ISSUE THREAD

**Issue by albertomolina** [iesgn/openstack-debian-ansible#19]
Horizon from jessie-backports shows problems loading css and none is loaded.

**Comment by albertomolina** [comment]
This bug is related to django configuration, in particular to this step:
    /usr/share/openstack-dashboard/manage.py compress --force

Some similar bugs have been reported previously:
https://bugs.launchpad.net/mos/+bug/1482674
https://bugs.launchpad.net/mos/+bug/1470143
https://bugs.launchpad.net/django-openstack-auth/+bug/1498408

**Comment by albertomolina** [comment]
A loop was found in a link, that maybe is related to this bug:

    find: File system loop detected; `./openstack_dashboard/static/horizon/horizon' is part of the same file system loop as `./openstack_dashboard/static/horizon'.

Deleting it manually makes the css can be loaded successfully:

    rm /usr/share/openstack-dashboard/openstack_dashboard/static/horizon/horizon

This step must be examined carefully and incorporated to the horizon play

**Comment by josedom24** [comment]
I've done what you've mentioned, but I do not work for me. Do I have to do something else? I restarted apache2, but not working.

**Comment by josedom24** [comment]
I uninstalled OpenStack-dashboard, I have run the playbook again and it worked without deleting the file.

**Comment by albertomolina** [comment]
More Information. The issue is also related to django version used:
    
    apt-cache policy python-django
    python-django:
    Installed: 1.8.7-2~bpo8+1
    Candidate: 1.8.7-2~bpo8+1
    Version table:
     1.9-1 0
        600 http://http.debian.net/debian/ testing/main amd64 Packages
    *** 1.8.7-2~bpo8+1 0
        650 http://http.debian.net/debian/ jessie-backports/main amd64 Packages
        100 /var/lib/dpkg/status
     1.7.7-1+deb8u3 0
        700 http://security.debian.org/ jessie/updates/main amd64 Packages
     1.7.7-1+deb8u2 0
        700 http://http.debian.net/debian/ jessie/main amd64 Packages

importlib is not longer supported in Django 1.9 [1] and it causes a bug if this version of Django is used [2]

[1] https://docs.djangoproject.com/en/1.9/internals/deprecation/
[2] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=809575

So, we must use python-django from jessie or jessie-backports

**Comment by albertomolina** [comment]
Related issues appear when OpenStack mitaka is installed on Debian Stretch, the solution provided by mantainers is wait until OpenStack newton will be ready :-m

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=832338

At this moment the only way to have horizon on debian with official packages is using OpenStack Icehouse (!!!), time to switch to ubuntu? :_(

**Comment by albertomolina** [comment]
OpenStack Newton solves this issue (It's not time to switch to ubuntu :) )
