### ISSUE TITLE
keystone_population

### ISSUE THREAD

**Issue by josedom24** [iesgn/openstack-debian-ansible#21]
He actualizado el catálogo de endpoint, el openrc y el demo_openrc.

He accedido a la máquina y ejecutado:
```
openstack domain create --description "Default Domain" default
openstack: 'domain' is not an openstack command. See 'openstack --help'.

```
Parece que hemos instalado un cliente openstack en una versión más antigua.
Por otro lado viendo la documentación de ansible, hay que cambiar el role keystone_population y no utilizar el módulo keystone_user (qué esta obsoleto). Hay que utilizar os_keystone_domain, os_user, os_keystone_role, os_user_group, os_user_role, os_project , ...

**Comment by albertomolina** [comment]
La versión de openstack-client parece ser que es la de mitaka:

    root@mitaka:~# apt-cache policy python-openstackclient
    python-openstackclient:
    Installed: 2.3.0-3~bpo8+1
    Candidate: 2.3.0-3~bpo8+1
    Version table:
     *** 2.3.0-3~bpo8+1 0
        500 http://mitaka-jessie.pkgs.mirantis.com/debian/ jessie-mitaka-backports/main amd64 Packages
        100 /var/lib/dpkg/status
     1.7.1-1~bpo8+1 0
        100 http://soleares.gonzalonazareno.org/debian/ jessie-backports/main amd64 Packages
     0.4.0-1 0
        500 http://soleares.gonzalonazareno.org/debian/ jessie/main amd64 Packages

Hay que ver por qué no tiene la opción de crear dominio

**Comment by albertomolina** [comment]
No hay ningún error y la versión es la correcta. Resulta que las opciones de openstack client (y la ayuda) se modifican en función de la versión de la API que se esté utilizando y hay que declarar la variable de entorno OS_IDENTITY_API_VERSION:

    export OS_IDENTITY_API_VERSION=3

Y ya funciona correctamente
