### ISSUE TITLE
neutron database incomplete creation

### ISSUE THREAD

**Issue by albertomolina** [iesgn/openstack-debian-ansible#9]
During neutron configuration, tables in the database are created, but for some unknown reason these tables are incomplete.

It is possible to reinitialize the db structures with the command:

    neutron-db-manage --config-file /etc/neutron/neutron.conf \
    --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head

So we added it temporary to the playbooks.

**Comment by anegro** [comment]
Check out my new pull request.
I got rid of UTF8 error by doing:
~~~
- name: ensure glance database is present
  mysql_db: >
    name=glance
    encoding=utf8
    collation=utf8_general_ci
~~~

**Comment by albertomolina** [comment]
I don't think so Antonio, this issue is related to neutron database, but maybe it's not an issue but a feature :), because this command appears as a normal step in OpenStack Kilo installation (Go to " To finalize installation"):

http://docs.openstack.org/kilo/install-guide/install/apt/content/neutron-controller-node.html

I didn't see it before in OpenStack docs.

To close or not to close the issue, that's the question ...
